[package]
name = "reve-gui"
version = "0.1.0"
description = "A Tauri based GUI app that upscale images using Real-ESRGAN model."
authors = ["OLoKo64 <reinaldorozatoj.11cg1@aleeas.com>"]
license = "MIT"
repository = "https://github.com/OLoKo64/reve-gui"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2.1", features = ["api-all"] }
dirs = "4.0.0"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
